id: IAC3C338E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:20:07+00:00'
last_modified: '2022-06-10T10:10:05.243622+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9280
  title: འཛམ་གླིང་ཆེན་པོའི་རྒྱས་བཤད་སྣོད་བཅུད་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    79F9:
      image_group_id: I1KG9348
      title: ''
      total_pages: 260
      order: 1
      base_file: 79F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
